'use strict';

module.exports = [
  'ABASTIBLE',
  'APEX',
  'ATT',
  'AUTOGASCO',
  'BALTOLU',
  'CAVE',
  'CHILIN',
  'COC',
  'COMBUSTIBLES AMADE',
  'COMBUSTIBLES JCD',
  'COMERCIAL MAQUI',
  'COPEC',
  'CUSTOM SERVICE',
  'Combustible Alhue',
  'Combustibles Endless.com',
  'Combustibles Ortiz',
  'Coopeserau',
  'Cremaschi',
  'DELPA',
  'ECCO',
  'ECOGREEN LTDA.',
  'EL HUIQUE',
  'ENERSUR S.A.',
  'FACAZ',
  'HN',
  'HOLA!',
  'J Allel',
  'JLC',
  'LIDER S.A.',
  'LIPIGAS',
  'PETROBRAS',
  'PETROJAC',
  'PETRONEXT',
  'Puma Verde',
  'Rafael Letelier Yañez y Cia Ltda',
  'SERVICENTRO LEAL',
  'SERVICENTRO SAN MIGUEL',
  'SERVICENTROS RABALME',
  'SESA',
  'SHELL',
  'SINHEL',
  'SOCORRO',
  'SUAREZ COMBUSTIBLES',
  'SURENERGY',
  'Sin Bandera',
  'TERPEL',
  'Uligas',
  'VIVA COMBUSTIBLES'
];
